package info.dylansouthard.StraysBookAPI.errors;
import java.util.Map;
import java.util.function.Supplier;

public interface ErrorCodes {
    String ANIMAL_NOT_FOUND = "ANIMAL_NOT_FOUND";
    String ANIMAL_NOT_ON_WATCHLIST = "ANIMAL_NOT_ON_WATCHLIST";
    String AUTH = "AUTH";
    String AUTH_FORBIDDEN = "AUTH_FORBIDDEN";
    String CARE_EVENTS_NOT_FOUND = "CARE_EVENTS_NOT_FOUND";
    String COULD_NOT_DELETE = "COULD_NOT_DELETE";
    String DELETE_VERIFIED_STERILIZATION_EVENT = "DELETE_VERIFIED_STERILIZATION_EVENT";
    String DUPLICATE_VACCINATION_EVENT = "DUPLICATE_VACCINATION_EVENT";
    String FAILED_LOGOUT = "FAILED_LOGOUT";
    String FAILED_TO_FETCH = "FAILED_TO_FETCH";
    String NOTIFICATIONS_FETCH_ERROR = "NOTIFICATIONS_FETCH_ERROR";
    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    String INVALID_COORDINATES = "INVALID_COORDINATES";
    String INVALID_CREATE = "INVALID_CREATE";
    String INVALID_PARAMS = "INVALID_PARAMS";
    String INVALID_VERIFICATION = "INVALID_VERIFICATION";
    String INVALID_UPDATE = "INVALID_UPDATE";
    String ITEM_EXISTS = "ITEM_EXISTS";
    String NO_VACCINATION_FOUND = "NO_VACCINATION_FOUND";
    String RECENT_CARE_EVENT_EXISTS = "RECENT_CARE_EVENT_EXISTS";
    String UPLOAD_ERROR = "UPLOAD_ERROR";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
}
